# Generated by Django 5.0.3 on 2024-04-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surface", models.FloatField()),
                ("usage", models.IntegerField()),
                ("periode_de_reference", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surface", models.FloatField()),
                ("usage", models.IntegerField()),
                (
                    "bat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.bat"
                    ),
                ),
            ],
        ),
    ]
