# Generated by Django 5.0.3 on 2024-04-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bat",
            new_name="Batiment",
        ),
    ]
