# Generated by Django 5.0.3 on 2024-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_bat_batiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batiment",
            name="surface",
            field=models.FloatField(default=None),
        ),
    ]
