# Generated by Django 5.0.3 on 2024-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_batiment_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batiment",
            name="surface",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="batiment",
            name="usage",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
